language: php


notifications:
  on_success: never
  on_failure: change

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  
env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - composer install

script:
    - vendor/bin/phpunit
