name: view-shortcodes plugin test

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4']
        wp: ['latest']
        experimental: [false]

    name: "PHP ${{ matrix.php }} - WP ${{ matrix.wp }}"
    continue-on-error: ${{ matrix.experimental }}

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mysqli

      - name: Set up WordPress
        run: phpunit/install.sh wordpress_test root '' 127.0.0.1:3306 ${{ matrix.wp }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1
        with:
          composer-options: --ignore-platform-reqs

      - name: Run the unit tests - single site
        run: vendor/bin/phpunit

      - name: Run the unit tests - multisite
        run: vendor/bin/phpunit
        env:
          WP_MULTISITE: 1
